runtime: python310
entrypoint: gunicorn -b :$PORT FinalProject.wsgi

env_variables:
  DJANGO_SETTINGS_MODULE: "FinalProject.settings"

handlers:
  - url: /static
    static_dir: static/
  - url: /.*
    script: auto
